### PR TITLE
Added missing secondary fire button to 4D Warriors

### PR DESCRIPTION
**Pull request by Left-Empty**
Hoping I did this right, took me nearly a month to figure it out XD

### CODE REVIEW

**Comment by JimmyStones** [comment]
That's bad luck - you did it right, but I got a change to the same line in last night so there is a merge conflict!

If you check the main branch and add the missing pause button on the end and push again your PR should be good to go :)

**Comment by Left-Empty** [comment]
I'll just close this because even though I updated the mra as you explained (thank you, by the way!), I'm too old and have too little patience for the github interface's insanity!

**Comment by JimmyStones** [comment]
Hah, fair enough - I need to do another PR later to fix some CRCs in another MRA, so I'll bash that button in for you then.

**Comment by Left-Empty** [comment]
Thank you kindly, I appreciate it very much!

**Pull request closed without merging**
